// Auto-generated by https://github.com/react-spring/gltfjsx

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Laptop(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/scene.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="OSG_Scene">
        <group name="RootNode_(gltf_orientation_matrix)" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="RootNode_(model_correction_matrix)">
            <group name="1930ef56796542c390ddf4dcc177094cfbx" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode">
                <group name="laptoppolySurface432">
                  <mesh
                    material={materials['laptoplambert2']}
                    geometry={nodes['laptoppolySurface432_laptoplambert2_0'].geometry}
                    name="laptoppolySurface432_laptoplambert2_0"
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </scene>
    </group>
  )
}
